// ═══════════════════════════════════════════════
//  MYSTIC PICK — Full Tarot Deck + Content Library
// ═══════════════════════════════════════════════

// ── MAJOR ARCANA (22) ────────────────────────────
const MAJOR_ARCANA = [
  {
    id: 0, name: "The Fool", suit: "major", num: "0",
    emoji: "🌬️",
    upright: "A new journey is beginning — one you could not have planned for. The universe is inviting you to step off the known cliff with open arms and trust that the ground will rise to meet you. Your innocence here is not naivety; it is courage in its purest form. Say yes before you feel ready.",
    reversed: "Recklessness is masquerading as freedom. Pause before leaping. There is a difference between brave spontaneity and ignoring every available signal. Ask yourself: what am I avoiding by rushing forward? The real leap may be inward, not outward.",
    keywords: ["New Beginnings", "Freedom", "Innocence"]
  },
  {
    id: 1, name: "The Magician", suit: "major", num: "I",
    emoji: "✨",
    upright: "Everything you need is already in your hands. You are in a rare moment of complete creative power — your thoughts, words, actions, and emotions are aligned. The universe is holding the door open. Walk through it with intention. What you focus on now, you will manifest.",
    reversed: "Your gifts are going unused, or worse, being misdirected. There may be self-doubt posing as reason, or a temptation to use your abilities to manipulate rather than create. Come back to your authentic power. It does not need tricks to work.",
    keywords: ["Manifestation", "Willpower", "Skill"]
  },
  {
    id: 2, name: "The High Priestess", suit: "major", num: "II",
    emoji: "🌊",
    upright: "Not everything is meant to be understood yet — and that is the message. Sit in the not-knowing. The High Priestess guards the threshold between what is seen and what is sensed. Your intuition is louder than logic right now. Trust the quiet voice over the loud one.",
    reversed: "You are dismissing your inner knowing in favour of external validation. Someone or something has convinced you that you cannot trust yourself. You can. The silence you keep avoiding is exactly where your answer lives.",
    keywords: ["Intuition", "Mystery", "Inner Knowing"]
  },
  {
    id: 3, name: "The Empress", suit: "major", num: "III",
    emoji: "🌺",
    upright: "You are entering a season of lush abundance — emotionally, creatively, perhaps even materially. The Empress asks you to stop apologising for your needs and start nourishing them. Rest is not laziness. Beauty is not frivolity. Pleasure is not a reward; it is a right.",
    reversed: "Somewhere, your self-worth has become entangled with how much you produce or give. You cannot pour from an empty vessel, and right now yours is running low. Return to the basics: rest, nourishment, gentle self-care. Abundance begins in the body.",
    keywords: ["Abundance", "Fertility", "Nurturing"]
  },
  {
    id: 4, name: "The Emperor", suit: "major", num: "IV",
    emoji: "🏛️",
    upright: "Structure is not the enemy of freedom — it is the scaffold that makes it possible. You are being called to take authority over your life: set the boundaries, make the plans, hold the line. Leadership is needed here, and it begins with leading yourself first.",
    reversed: "Control is being wielded where it does not belong, either by you or over you. Examine where rigidity has replaced wisdom. True authority does not require force. Soften without collapsing.",
    keywords: ["Authority", "Structure", "Stability"]
  },
  {
    id: 5, name: "The Hierophant", suit: "major", num: "V",
    emoji: "🕯️",
    upright: "Tradition, mentorship, and shared wisdom are being highlighted. There is value in learning from those who have walked this path before you. This may also point toward a commitment, ritual, or formal union of some kind. What do you believe — really believe — when no one is watching?",
    reversed: "You are outgrowing the beliefs you inherited. This is not betrayal — it is evolution. Question the rules you follow out of habit rather than conviction. Your spiritual or philosophical path may be asking for a radical revision.",
    keywords: ["Tradition", "Mentorship", "Belief"]
  },
  {
    id: 6, name: "The Lovers", suit: "major", num: "VI",
    emoji: "🌸",
    upright: "A profound choice lies before you — one that will shape your values, not just your circumstances. This card is less about romance and more about alignment: are you choosing what truly resonates with your soul, or what looks good on the surface? The heart knows. Follow it.",
    reversed: "Misalignment. A relationship, decision, or internal value system is out of harmony with who you actually are. There may be dissonance between what you want and what you feel you 'should' want. Honesty — especially with yourself — is the only way through.",
    keywords: ["Choice", "Alignment", "Love"]
  },
  {
    id: 7, name: "The Chariot", suit: "major", num: "VII",
    emoji: "⚡",
    upright: "Victory through discipline, not luck. You have the power to override every obstacle if you maintain your focus and harness your will. The Chariot does not stop for self-doubt. Keep moving, stay centred, and claim the outcome you have been working toward.",
    reversed: "You are fighting in too many directions at once. Your energy is scattered and your drive is going nowhere productive. Before you push forward, you must first decide where 'forward' actually is.",
    keywords: ["Willpower", "Victory", "Control"]
  },
  {
    id: 8, name: "Strength", suit: "major", num: "VIII",
    emoji: "🌿",
    upright: "The greatest power is the kind that does not need to announce itself. You are stronger than you know — not in spite of your sensitivity, but because of it. Compassion, patience, and inner calm are your real weapons here. Use them.",
    reversed: "Self-doubt is louder than it should be right now. You may be surrendering your power to someone or something that does not deserve it, or overcompensating through aggression when gentleness would serve better. Your strength is always there — listen for it.",
    keywords: ["Inner Strength", "Courage", "Patience"]
  },
  {
    id: 9, name: "The Hermit", suit: "major", num: "IX",
    emoji: "🔦",
    upright: "The answer you are looking for cannot be found in the noise. Retreat — not in defeat, but in wisdom. Spend time alone with your thoughts. Let the surface-level distractions fall away. What remains when everything else is quiet is the truest version of you.",
    reversed: "Isolation has tipped into loneliness, or the inner work is being avoided entirely. You cannot think your way out of everything. At some point, you will need to return to the world and let others in.",
    keywords: ["Solitude", "Inner Guidance", "Wisdom"]
  },
  {
    id: 10, name: "Wheel of Fortune", suit: "major", num: "X",
    emoji: "🌀",
    upright: "The wheel is turning in your favour. What has felt stagnant is beginning to move. Cycles complete, seasons change, and the luck you have been waiting for is closer than it appears. Stay ready — opportunity often arrives in ordinary disguise.",
    reversed: "A turning point is near, but resistance is making it harder than it needs to be. You may be fighting the natural current of change. Whatever is ending was meant to end. Let it.",
    keywords: ["Cycles", "Fate", "Change"]
  },
  {
    id: 11, name: "Justice", suit: "major", num: "XI",
    emoji: "⚖️",
    upright: "Truth, fairness, and consequence are in play. You will receive exactly what this situation deserves — no more, no less. If you have acted with integrity, rest easy. If not, this is a moment for honest accounting before the universe does it for you.",
    reversed: "Something is out of balance and accountability is being avoided. You may be rationalising an unjust position or being treated unfairly without recourse. In either case, truth will eventually prevail — the question is who acknowledges it first.",
    keywords: ["Justice", "Truth", "Accountability"]
  },
  {
    id: 12, name: "The Hanged Man", suit: "major", num: "XII",
    emoji: "🌒",
    upright: "Surrender is not failure — it is the most profound act of trust. You are being asked to pause, to wait, to see the world from an entirely different angle. What looks like delay is actually deep preparation. Something must be released before the next thing can arrive.",
    reversed: "You are stalling in a situation that requires action. The pause has gone past useful and become avoidance. The sacrifice being resisted is necessary. What is the cost of continuing to hold on?",
    keywords: ["Surrender", "Pause", "New Perspective"]
  },
  {
    id: 13, name: "Death", suit: "major", num: "XIII",
    emoji: "🌑",
    upright: "Not physical death — the death of what was. A chapter is closing with finality, and this is not a tragedy; it is a clearing. Something must end for the next beautiful thing to have room to exist. Grieve what is leaving, then turn toward what is coming.",
    reversed: "You are clinging to something that has already ended. The refusal to let go is costing you the future. Change is being resisted at great personal expense. The transformation is happening regardless — the question is whether you will move with it or be dragged.",
    keywords: ["Transformation", "Endings", "Change"]
  },
  {
    id: 14, name: "Temperance", suit: "major", num: "XIV",
    emoji: "🌤️",
    upright: "You are being asked to find the middle path — not the exciting extreme, not the safe avoidance, but the quiet, steady balance between them. Healing is happening right now, often slowly and invisibly. Trust the process. What you are blending is becoming something new.",
    reversed: "Excess in some area is destabilising your peace. Too much of something — or not enough — is throwing off the balance. Look at where you are operating from extremes and ask what 'just enough' would feel like.",
    keywords: ["Balance", "Patience", "Healing"]
  },
  {
    id: 15, name: "The Devil", suit: "major", num: "XV",
    emoji: "🔗",
    upright: "You are more free than you feel. The chains in this image are loose — they could be lifted. But you have been convinced, by habit or fear or desire, that you cannot leave. What are you attached to that is shrinking your life? Naming it is already the beginning of release.",
    reversed: "Liberation is near. A pattern that has had power over you is beginning to lose its grip. The addiction, the toxic bond, the limiting belief — you are starting to see it for what it is. Keep going. The door is open.",
    keywords: ["Bondage", "Shadow", "Liberation"]
  },
  {
    id: 16, name: "The Tower", suit: "major", num: "XVI",
    emoji: "🔥",
    upright: "Something built on an unstable foundation is coming down. This is terrifying and necessary. The Tower does not destroy what is true — only what was never meant to stand. What emerges from this rubble will be real in a way the previous structure never was.",
    reversed: "You are delaying a necessary upheaval out of fear. The collapse is inevitable — the only variable is how long you postpone it. Alternatively, you have survived a major disruption and are now rebuilding. Either way, the worst is either coming or passing.",
    keywords: ["Upheaval", "Revelation", "Chaos"]
  },
  {
    id: 17, name: "The Star", suit: "major", num: "XVII",
    emoji: "⭐",
    upright: "After everything that has happened, hope arrives. Quietly, persistently, without fanfare. You are being renewed at a level deeper than you can fully perceive right now. Trust this gentle feeling. It is not wishful thinking — it is accurate perception.",
    reversed: "Hopelessness or disillusionment has settled in, and it is distorting your view of what is possible. You are not seeing clearly right now. The light has not gone out; it is just temporarily obscured. Be gentle with yourself as you wait for visibility to return.",
    keywords: ["Hope", "Renewal", "Inspiration"]
  },
  {
    id: 18, name: "The Moon", suit: "major", num: "XVIII",
    emoji: "🌙",
    upright: "Things are not as they appear. Illusions, fears, and projections are active — yours and others'. Navigate carefully, with your inner compass rather than your anxious mind. The Moon illuminates the unconscious, and right now, something buried is asking to be seen.",
    reversed: "Confusion is beginning to clear. A deception — whether external or self-created — is being exposed. The fog is lifting. What you see in the emerging clarity may be uncomfortable, but it is real, and real is always more workable than imagined.",
    keywords: ["Illusion", "Subconscious", "Fear"]
  },
  {
    id: 19, name: "The Sun", suit: "major", num: "XIX",
    emoji: "☀️",
    upright: "Pure, unqualified good. Clarity, joy, vitality, and the warmth of being fully alive. This card does not hedge its message — things are going well, or they are about to. Step into the light without apologising for it. You are allowed to be happy.",
    reversed: "Joy is being blocked — perhaps by pessimism, perfectionism, or the belief that happiness must be earned. The Sun's light is still there; you have simply closed the curtains. What small act today could let a little light back in?",
    keywords: ["Joy", "Clarity", "Success"]
  },
  {
    id: 20, name: "Judgement", suit: "major", num: "XX",
    emoji: "🎺",
    upright: "A calling is sounding. Not a gentle suggestion — a summons. Something in you that has been dormant is waking up, and the universe is asking whether you are ready to answer. This is a moment of profound reckoning and renaissance. Rise.",
    reversed: "The call is being heard but not answered. Self-doubt, shame, or the fear of how others will respond is keeping you small. What would it mean to truly forgive yourself and begin again?",
    keywords: ["Awakening", "Reckoning", "Renewal"]
  },
  {
    id: 21, name: "The World", suit: "major", num: "XXI",
    emoji: "🪐",
    upright: "Completion. Integration. The realisation that you have, in some essential way, arrived. What you began — whether a project, a period of growth, or a chapter of your life — is coming to a whole and beautiful close. Celebrate this. Then prepare for the next beautiful beginning.",
    reversed: "You are close to completion but something is preventing the final step — perfectionism, fear of what comes next, or an unwillingness to declare 'enough.' The finish line is right there. Cross it.",
    keywords: ["Completion", "Integration", "Achievement"]
  },
];

// ── MINOR ARCANA GENERATOR ───────────────────────
function makeCups() {
  return [
    { id:100, name:"Ace of Cups", suit:"cups", num:"Ace", emoji:"💙",
      upright:"A new emotional beginning is flooding in — love, creativity, spiritual connection, or healing. Your heart is opening to receive something it has longed for. Do not second-guess this feeling. Let it in.",
      reversed:"Emotions are blocked or being suppressed. A relationship or creative well feels dry. The source has not run out — but something is preventing flow. Identify the blockage and gently remove it.",
      keywords:["New Love","Emotion","Overflow"]},
    { id:101, name:"Two of Cups", suit:"cups", num:"II", emoji:"💑",
      upright:"A deep and reciprocal connection is forming or deepening. Whether romantic or platonic, this bond is one of true mutual recognition — two people choosing each other in full awareness. This is rare. Honour it.",
      reversed:"Disharmony in a partnership. Miscommunication, incompatibility, or one person giving far more than the other. Return to honest conversation. Connection cannot thrive in silence.",
      keywords:["Partnership","Harmony","Union"]},
    { id:102, name:"Three of Cups", suit:"cups", num:"III", emoji:"🥂",
      upright:"Joy multiplied by community. Celebration, friendship, and the deep nourishment of belonging. You are not meant to carry this life alone — let others in. Right now, the people around you are a gift.",
      reversed:"Overindulgence or social exhaustion. Perhaps you have been giving to your community while neglecting yourself, or being surrounded by people who drain rather than fill. Choose your circle with intention.",
      keywords:["Celebration","Community","Joy"]},
    { id:103, name:"Four of Cups", suit:"cups", num:"IV", emoji:"🙏",
      upright:"You are so focused on what is missing that you are missing what is being offered. Apathy and introspection have their place, but the cup being extended to you right now deserves your attention. Look up.",
      reversed:"Apathy is beginning to lift. A period of withdrawal is ending and you are re-engaging with life. Something that felt unimportant is revealing its value. Welcome back.",
      keywords:["Apathy","Contemplation","Reevaluation"]},
    { id:104, name:"Five of Cups", suit:"cups", num:"V", emoji:"😢",
      upright:"Grief is real and it deserves space. You have lost something — or someone — and the sadness is appropriate. But notice the cups still standing behind you. Loss and continuation exist simultaneously. Feel what needs to be felt, then turn around.",
      reversed:"Grief is beginning to integrate. You are accepting a loss and starting to look forward. The path is not the same as it was, but it is still a path, and it leads somewhere worth going.",
      keywords:["Loss","Grief","Regret"]},
    { id:105, name:"Six of Cups", suit:"cups", num:"VI", emoji:"🌼",
      upright:"Nostalgia, innocence, and the sweetness of what has been. An old connection may reappear, or a childlike joy is asking to be reclaimed. You are allowed to return to the things that made you feel safe and loved.",
      reversed:"You are living too much in the past — either idealising it or being haunted by it. The present moment contains its own gifts. Can you find one today?",
      keywords:["Nostalgia","Innocence","Reunion"]},
    { id:106, name:"Seven of Cups", suit:"cups", num:"VII", emoji:"🌈",
      upright:"Too many possibilities are pulling you in too many directions. Fantasy is rich, but eventually a choice must be made. Not every option can be pursued at once. Which one, when you quiet the noise, truly calls to you?",
      reversed:"Clarity is returning after a period of confusion or fantasy. You are beginning to separate the real from the imagined and ground yourself in what is genuinely possible. This is wisdom, not disappointment.",
      keywords:["Choices","Fantasy","Illusion"]},
    { id:107, name:"Eight of Cups", suit:"cups", num:"VIII", emoji:"🚶",
      upright:"It takes tremendous courage to walk away from something that still holds emotional meaning. But you have outgrown this — the cups here are full, but they are no longer yours. Your deeper self is calling you toward something truer. Go.",
      reversed:"You are staying in a situation you have already emotionally left. Fear of the unknown, or of hurting others, is keeping you tethered to what needs to be released. The leaving is not a betrayal. It is an act of love for yourself.",
      keywords:["Abandonment","Retreat","Walking Away"]},
    { id:108, name:"Nine of Cups", suit:"cups", num:"IX", emoji:"😊",
      upright:"The wish card. Something you have deeply wanted is coming true, or is very close. This is the card of emotional fulfilment and satisfaction — not perfection, but the genuine feeling that life is good. Receive this with gratitude, not suspicion.",
      reversed:"Superficial satisfaction — things look good on the outside but feel hollow within. Or perhaps greed or excess is dulling the appreciation of what is genuinely present. Look inward. What does true contentment feel like for you?",
      keywords:["Fulfilment","Wishes","Satisfaction"]},
    { id:109, name:"Ten of Cups", suit:"cups", num:"X", emoji:"🏡",
      upright:"Lasting emotional harmony. This is not a passing good mood — it is deep, sustained wellbeing in your relationships and home life. What you have built together is real. Appreciate it fully, because this is what it all comes down to.",
      reversed:"The surface looks harmonious but underneath there is tension, disconnect, or unmet needs. True happiness in relationship requires honesty, not performance. Speak what is real.",
      keywords:["Happiness","Harmony","Family"]},
    { id:110, name:"Page of Cups", suit:"cups", num:"Page", emoji:"🐟",
      upright:"A message from the heart — unexpected, tender, and possibly surprising. This page brings creative inspiration, emotional openness, and the willingness to feel without armour. Be receptive. Something beautiful is trying to reach you.",
      reversed:"Emotional immaturity or moodiness is causing disruption. Feelings are being dramatised rather than processed. Take a breath before reacting. Not every emotion needs to become a scene.",
      keywords:["Messages","Creativity","Sensitivity"]},
    { id:111, name:"Knight of Cups", suit:"cups", num:"Knight", emoji:"🌊",
      upright:"Romance, charm, and idealism in motion. Someone is arriving — or you are becoming someone — who follows the heart wherever it leads. Pursue what moves you with full commitment, even if it looks impractical to others.",
      reversed:"Moodiness, escapism, or romantic idealism that refuses contact with reality. Big feelings are being dramatised into stories. Ground yourself before acting on an emotional impulse.",
      keywords:["Romance","Following the Heart","Idealism"]},
    { id:112, name:"Queen of Cups", suit:"cups", num:"Queen", emoji:"🌺",
      upright:"Deep emotional intelligence, compassion, and the rare ability to hold space for others without losing yourself. This queen feels everything and is not overwhelmed by it. Her wisdom comes from the water — fluid, deep, and clear.",
      reversed:"Emotional overwhelm or co-dependency. Feelings are clouding judgment, or you are absorbing everyone else's emotions at the expense of your own clarity. Return to your own shore.",
      keywords:["Compassion","Empathy","Emotional Depth"]},
    { id:113, name:"King of Cups", suit:"cups", num:"King", emoji:"🌊",
      upright:"Emotional mastery — not the suppression of feeling, but the ability to feel deeply while remaining steady. This king leads with the heart AND the mind. He is present, calm, and trustworthy in turbulent waters.",
      reversed:"Emotional manipulation or volatility. Someone is using feelings as a tool for control, or suppressing emotions until they leak out sideways. True emotional maturity is being called for here.",
      keywords:["Emotional Mastery","Calm","Wisdom"]},
  ];
}

function makePentacles() {
  return [
    { id:200, name:"Ace of Pentacles", suit:"pentacles", num:"Ace", emoji:"🪙",
      upright:"A new material opportunity is presenting itself — a seed of financial growth, a new job, a business idea, or a tangible gift from the universe. This is real potential, not a dream. Plant it carefully and tend it with patience.",
      reversed:"A financial or material opportunity is being missed, perhaps through fear or poor timing. Or the foundation of something new is unstable. Build carefully before expanding.",
      keywords:["New Opportunity","Prosperity","Material Beginnings"]},
    { id:201, name:"Two of Pentacles", suit:"pentacles", num:"II", emoji:"🤹",
      upright:"You are managing more than it appears — and doing it well. Life is requiring constant adjustment and balance. This is not sustainable forever, but you are handling it with more grace than you give yourself credit for. Just don't drop the important one.",
      reversed:"The juggling act is becoming unsustainable. Something has to give — the question is what. Prioritise ruthlessly, delegate where possible, and release the illusion that you must manage everything alone.",
      keywords:["Balance","Multitasking","Adaptability"]},
    { id:202, name:"Three of Pentacles", suit:"pentacles", num:"III", emoji:"🏗️",
      upright:"Collaboration and skilled craftsmanship. Your work is being seen and valued. This is not the time to go it alone — the right people are available to build something together that none of you could create individually. Let their expertise complement yours.",
      reversed:"Poor teamwork, lack of appreciation for skill, or refusing to collaborate out of pride. The work suffers when the ego insists on going alone. What would you gain from asking for help?",
      keywords:["Teamwork","Skill","Recognition"]},
    { id:203, name:"Four of Pentacles", suit:"pentacles", num:"IV", emoji:"💼",
      upright:"Financial stability and the wisdom to protect what you have built. There is nothing wrong with holding on when you have earned something. But examine whether security has tipped into hoarding — whether fear is preventing generosity or growth.",
      reversed:"Gripping too tightly. Financial anxiety or the fear of loss is causing you to hold on in ways that are actually counterproductive. Money, like water, must flow to remain fresh. Release a little.",
      keywords:["Security","Control","Possession"]},
    { id:204, name:"Five of Pentacles", suit:"pentacles", num:"V", emoji:"❄️",
      upright:"A period of material hardship or feeling excluded from abundance. This is painful and real — but notice the warm light of the church window. Help exists. The question is whether you are willing to accept it or whether pride is keeping you out in the cold.",
      reversed:"Recovery is beginning. The worst of a financial or material difficulty is passing, and support — material or otherwise — is becoming available. Let yourself receive it.",
      keywords:["Hardship","Poverty","Exclusion"]},
    { id:205, name:"Six of Pentacles", suit:"pentacles", num:"VI", emoji:"🤲",
      upright:"The flow of giving and receiving is in balance. Generosity — whether you are the giver or receiver — is the theme. Be mindful of the power dynamics in this exchange. Giving from a place of genuine abundance is different from giving to feel superior.",
      reversed:"Strings are attached to this generosity, or you are giving from depletion rather than overflow. Examine the motivations on both sides of this exchange.",
      keywords:["Generosity","Charity","Balance"]},
    { id:206, name:"Seven of Pentacles", suit:"pentacles", num:"VII", emoji:"🌱",
      upright:"You have done the work and now you wait. The harvest is coming, but it is not ready yet. This is a season of patient tending, of trusting that the effort you have already made is enough. Do not uproot the seeds to check their progress.",
      reversed:"Impatience is undermining the work. Or the work you have put in is not aligned with the results you actually want. Reassess: are you tending the right garden?",
      keywords:["Patience","Investment","Long-term View"]},
    { id:207, name:"Eight of Pentacles", suit:"pentacles", num:"VIII", emoji:"⚙️",
      upright:"Mastery through dedication. You are — or need to be — fully focused on developing your craft. This card rewards disciplined, consistent effort. The universe does not shortcut genuine skill. Keep going. The repetition is the point.",
      reversed:"Perfectionism is blocking progress, or skills are being applied to the wrong work entirely. Are you polishing something that should simply be released?",
      keywords:["Mastery","Diligence","Craftsmanship"]},
    { id:208, name:"Nine of Pentacles", suit:"pentacles", num:"IX", emoji:"🌿",
      upright:"You have earned this. Financial independence, self-sufficiency, and the quiet pleasure of being able to enjoy what you have worked for. This card asks you to appreciate your own achievement without waiting for someone else to validate it.",
      reversed:"Financial dependence or the uncomfortable feeling that your current comfort has not been earned on your own terms. What would genuine self-sufficiency look like for you?",
      keywords:["Abundance","Independence","Luxury"]},
    { id:209, name:"Ten of Pentacles", suit:"pentacles", num:"X", emoji:"🏰",
      upright:"Generational wealth, legacy, and the deep satisfaction of long-term stability. What you are building now is not just for you — it is for those who come after. You are creating something that will outlast the effort it takes to make it.",
      reversed:"Family conflict over money, or the realisation that material success alone does not create the legacy you truly want to leave. What matters most when the wealth is stripped away?",
      keywords:["Legacy","Wealth","Family"]},
    { id:210, name:"Page of Pentacles", suit:"pentacles", num:"Page", emoji:"📚",
      upright:"A new area of learning or financial interest is beginning to take shape. This page brings the energy of a student — curious, grounded, and willing to start from scratch. What new skill or opportunity is asking for your serious attention?",
      reversed:"Procrastination or a lack of follow-through is preventing real progress. Ideas without application remain ideas. Take one concrete, grounded step today.",
      keywords:["New Skills","Ambition","Study"]},
    { id:211, name:"Knight of Pentacles", suit:"pentacles", num:"Knight", emoji:"🐎",
      upright:"Slow, methodical, and utterly reliable. This knight does not rush, does not cut corners, and does not abandon what he starts. His pace may frustrate those around him, but his results are undeniable. Be this energy.",
      reversed:"Stubbornness or excessive caution is slowing progress to a standstill. Not all risk is recklessness. Sometimes the most productive move is to move.",
      keywords:["Responsibility","Work Ethic","Dedication"]},
    { id:212, name:"Queen of Pentacles", suit:"pentacles", num:"Queen", emoji:"🌻",
      upright:"Practical, grounded, generous, and deeply nourishing. This queen knows how to create comfort, manage resources wisely, and care for those around her without losing herself in the process. She is abundance embodied in a sensible form.",
      reversed:"Overwork, financial anxiety, or losing yourself in the caretaking of others. Your practical wisdom is a gift — just don't forget to apply it to yourself as well.",
      keywords:["Practicality","Nurturing","Financial Security"]},
    { id:213, name:"King of Pentacles", suit:"pentacles", num:"King", emoji:"👑",
      upright:"Mastery of the material world, earned through patient, disciplined effort. This king is generous with what he has built, but he built it with extraordinary consistency. What in your life would benefit from his kind of long-view, no-shortcuts approach?",
      reversed:"Greed, materialism, or using wealth and resources as a means of control. The richest life contains more than numbers.",
      keywords:["Wealth","Discipline","Leadership"]},
  ];
}

function makeSwords() {
  return [
    { id:300, name:"Ace of Swords", suit:"swords", num:"Ace", emoji:"⚔️",
      upright:"Radical clarity. A truth you have been circling is about to cut through the fog with precision. This is the gift of a sharp mind — the ability to see things exactly as they are, without softening or distortion. Speak it. Act on it.",
      reversed:"Mental confusion, dishonesty, or a truth that is being wielded as a weapon. Clarity without compassion can wound. Use your insight wisely.",
      keywords:["Clarity","Truth","Breakthrough"]},
    { id:301, name:"Two of Swords", suit:"swords", num:"II", emoji:"🙈",
      upright:"A decision is being avoided because both options have costs. The blindfold here is self-imposed. You already know more than you are allowing yourself to see. The discomfort of choosing is less than the discomfort of perpetual indecision.",
      reversed:"The blindfold is coming off. A decision that has been avoided can no longer be postponed. Information is arriving that changes everything. Be ready to see clearly and act accordingly.",
      keywords:["Indecision","Avoidance","Stalemate"]},
    { id:302, name:"Three of Swords", suit:"swords", num:"III", emoji:"💔",
      upright:"Heartbreak, grief, and the pain of betrayal or disappointment. This card does not minimize what you are feeling — it validates it. Pain this sharp is real. But it is also, eventually, survivable. Feeling it fully is the only way through.",
      reversed:"Healing is happening. The sharpest part of the grief is beginning to soften. You are integrating this loss and finding your way back to yourself. Give yourself the credit this takes.",
      keywords:["Heartbreak","Grief","Sorrow"]},
    { id:303, name:"Four of Swords", suit:"swords", num:"IV", emoji:"😴",
      upright:"Rest is not optional right now — it is essential. Your mind needs stillness, your nervous system needs quiet, your body needs recovery. This is not laziness; it is strategic withdrawal. Honour the need to pause.",
      reversed:"Rest has become avoidance. The withdrawal that was once restorative has tipped into stagnation. It is time to re-engage with life, gently but deliberately.",
      keywords:["Rest","Recovery","Meditation"]},
    { id:304, name:"Five of Swords", suit:"swords", num:"V", emoji:"😤",
      upright:"Conflict with a hollow victory — someone has won the argument but lost the relationship. Ask yourself: what are you actually fighting for, and is the cost of winning worth it? Sometimes walking away with your integrity is the only real win.",
      reversed:"The aftermath of conflict. There may be an opportunity to reconcile or move forward without further damage. Swallow what pride remains and consider what you actually want this to look like.",
      keywords:["Conflict","Defeat","Loss"]},
    { id:305, name:"Six of Swords", suit:"swords", num:"VI", emoji:"⛵",
      upright:"You are moving away from turbulence toward calmer waters. This transition may feel like a loss, but it is a necessary one. The difficult part is behind you; ahead is a quieter shore. The passage is underway, even if it does not feel smooth yet.",
      reversed:"Delayed or resisted transition. You may be trying to turn back toward what was familiar but is no longer safe. Or the waters are unexpectedly choppy mid-crossing. Keep going. The other side is real.",
      keywords:["Transition","Moving On","Recovery"]},
    { id:306, name:"Seven of Swords", suit:"swords", num:"VII", emoji:"🎭",
      upright:"Strategy, stealth, and the wisdom to pick your battles. Not every confrontation needs to be direct. Sometimes the most intelligent move is to quietly gather what you need and exit without ceremony. But examine your motivations carefully.",
      reversed:"Deception is being uncovered — either yours or another's. A strategy that has relied on avoidance or dishonesty is no longer tenable. Come clean before the situation does it for you.",
      keywords:["Strategy","Deception","Cunning"]},
    { id:307, name:"Eight of Swords", suit:"swords", num:"VIII", emoji:"🕸️",
      upright:"You feel trapped, but the trap is largely constructed in your own mind. The restrictions you believe are holding you are far more permeable than they appear. One small movement — one honest conversation, one changed belief — can begin the whole unravelling.",
      reversed:"Freedom is within reach. You are beginning to recognise that the limitations binding you are not as absolute as they felt. Move toward the opening, however small.",
      keywords:["Restriction","Self-imprisonment","Fear"]},
    { id:308, name:"Nine of Swords", suit:"swords", num:"IX", emoji:"😱",
      upright:"The darkest hour is the mind at 3am. Anxiety, sleeplessness, and catastrophic thinking are at their loudest right now. Most of what you are fearing has not happened and will not. But the suffering is real. Seek gentle support — you do not have to carry this alone.",
      reversed:"The anxiety is beginning to ease. What felt unsurvivable is becoming manageable. The morning, both literal and figurative, is coming. Reach for any small comfort available.",
      keywords:["Anxiety","Nightmare","Mental Anguish"]},
    { id:309, name:"Ten of Swords", suit:"swords", num:"X", emoji:"🌅",
      upright:"A decisive ending. Something has been cut away — perhaps painfully — but it is done. The sun rises on the horizon of this card. What has ended cannot be continued, and this, though devastating, is also a release. The lowest point contains within it the turning point.",
      reversed:"Recovery from a devastating blow. The rock bottom has been hit, and now the only direction is up. The worst is genuinely over. Begin again, knowing exactly how strong you are.",
      keywords:["Endings","Betrayal","Rock Bottom"]},
    { id:310, name:"Page of Swords", suit:"swords", num:"Page", emoji:"🌬️",
      upright:"Sharp-minded, curious, and ready to challenge any assumption. This page brings the energy of intellectual restlessness and the desire to understand everything. Use this energy to ask the harder questions. Truth, even when uncomfortable, is what you are after.",
      reversed:"Gossip, unnecessary conflict, or mental energy going in too many directions without producing anything useful. Channel the sharpness into something constructive.",
      keywords:["Curiosity","Truth-seeking","Intelligence"]},
    { id:311, name:"Knight of Swords", suit:"swords", num:"Knight", emoji:"⚡",
      upright:"Fast, decisive, and utterly fearless. This knight charges toward truth and action without hesitation. Use this energy when you have been too slow, too cautious, or too accommodating. Move. Decide. Speak.",
      reversed:"Recklessness, aggression, or words used as weapons. Speed without direction is dangerous. Slow down long enough to consider the full impact of your actions.",
      keywords:["Action","Ambition","Charge Forward"]},
    { id:312, name:"Queen of Swords", suit:"swords", num:"Queen", emoji:"🗡️",
      upright:"Clear-sighted, direct, and deeply intelligent. This queen has lived through enough to see clearly without bitterness. She does not soften hard truths, but she delivers them with precision rather than cruelty. Let her clarity guide you.",
      reversed:"Coldness, harshness, or the use of intelligence to wound rather than illuminate. The sharp mind is a tool, not a weapon. Check whether your clarity is serving others or just serving your ego.",
      keywords:["Clarity","Independence","Truth"]},
    { id:313, name:"King of Swords", suit:"swords", num:"King", emoji:"⚖️",
      upright:"Intellectual authority, ethical clarity, and the power to cut through complexity with precision. This king makes difficult decisions without flinching because he has already done the inner work of knowing his values. Aspire to this kind of clear-minded integrity.",
      reversed:"Tyranny of the intellect — using logic as a weapon, dismissing emotion as irrelevant, or making cold decisions without moral consideration. Intelligence without wisdom is dangerous.",
      keywords:["Authority","Logic","Ethical Clarity"]},
  ];
}

function makeWands() {
  return [
    { id:400, name:"Ace of Wands", suit:"wands", num:"Ace", emoji:"🔥",
      upright:"Ignition. A spark of inspiration, passion, or creative energy is being handed to you right now. This is raw potential — take it and run with it. The fire is real. What you do with it depends on how quickly you act.",
      reversed:"Creative blocks, false starts, or inspiration that fizzles before taking hold. What is dampening the spark? Find the source of the dampness before trying to light the fire again.",
      keywords:["Inspiration","New Venture","Spark"]},
    { id:401, name:"Two of Wands", suit:"wands", num:"II", emoji:"🌍",
      upright:"You are standing at the beginning of something large. The world is laid out before you and you are beginning to understand the full scope of what is possible. This requires not just dreaming but planning. What is your first concrete step toward the horizon?",
      reversed:"Fear of the unknown is preventing departure. The plan exists in your head but stays there. The vision has value only when it is matched with movement. What is actually stopping you?",
      keywords:["Vision","Planning","Future"]},
    { id:402, name:"Three of Wands", suit:"wands", num:"III", emoji:"⛵",
      upright:"Your ships are on the water. What you launched is now in motion, and the first results of your efforts are beginning to arrive. Expansion, both internal and external, is underway. Look farther than you usually allow yourself to. This is going somewhere.",
      reversed:"Delays, setbacks, or the frustration of plans that are not unfolding as expected. Adjust without abandoning. The destination is still real.",
      keywords:["Expansion","Progress","Foresight"]},
    { id:403, name:"Four of Wands", suit:"wands", num:"IV", emoji:"🎊",
      upright:"Celebration, homecoming, and the joy of a milestone reached. This is a moment to stop and mark what you have built — a relationship, a home, a foundation, an achievement. Do not move past this without ceremony.",
      reversed:"Instability in what should feel like home, either literally or emotionally. The celebration is incomplete or premature. Something in the foundation needs attention before the party can truly begin.",
      keywords:["Celebration","Home","Stability"]},
    { id:404, name:"Five of Wands", suit:"wands", num:"V", emoji:"⚔️",
      upright:"Productive tension, competition, or the chaos of too many people pulling in different directions. This conflict is not destructive — it is clarifying. The friction here is sharpening you. Just make sure the battle you're in is worth fighting.",
      reversed:"Conflict is cooling. A competitive situation is resolving, or you are finding ways to work with rather than against those around you. Peace is being negotiated.",
      keywords:["Competition","Conflict","Tension"]},
    { id:405, name:"Six of Wands", suit:"wands", num:"VI", emoji:"🏆",
      upright:"Public recognition and well-earned triumph. You have done something worth celebrating, and others are beginning to see it. Let yourself be seen in this moment. Success is not arrogance when it is genuinely earned.",
      reversed:"Ego or the fear of being visible is complicating a moment that should be joyful. Alternatively, external validation is becoming a dependency. The real victory is internal.",
      keywords:["Victory","Recognition","Success"]},
    { id:406, name:"Seven of Wands", suit:"wands", num:"VII", emoji:"🛡️",
      upright:"You are being challenged — possibly from multiple directions. Hold your ground. The position you have earned is worth defending, even when it is exhausting. Not everyone who questions your place is right. Stand firm.",
      reversed:"Defensiveness that has become counterproductive, or exhaustion from constantly fighting for your position. Is this battle still yours to fight? Sometimes strategic retreat is the most powerful move.",
      keywords:["Defense","Perseverance","Challenge"]},
    { id:407, name:"Eight of Wands", suit:"wands", num:"VIII", emoji:"💨",
      upright:"Swift movement. Things are accelerating. Communication is flying, decisions are resolving, and what has been slow is now fast. Get ready. The energy here asks for quick action and a willingness to move at the speed of what is arriving.",
      reversed:"Delays, miscommunication, or energy moving in too many directions at once. Something is stuck. Find the single point of resistance and remove it.",
      keywords:["Speed","Action","Swift Change"]},
    { id:408, name:"Nine of Wands", suit:"wands", num:"IX", emoji:"🏔️",
      upright:"You are battered but still standing. This is the last major test before completion, and you have everything required to pass it — including the wounds that prove you have not given up. One more push. You are closer than it feels.",
      reversed:"Paranoia, defensiveness, or the refusal to trust after being hurt. Past pain is colouring present perception. Not everything that approaches is a threat. Lower your guard long enough to let the good in.",
      keywords:["Resilience","Persistence","Last Stand"]},
    { id:409, name:"Ten of Wands", suit:"wands", num:"X", emoji:"😓",
      upright:"You are carrying too much. The weight is real, and it is excessive. This is a card of necessary redistribution — of asking who else can help carry this, what can be put down, what was never yours to begin with. You are strong enough to set things down.",
      reversed:"Release is beginning. Burdens are being dropped or delegated, and the relief of having less to carry is slowly becoming apparent. Let yourself feel how much lighter this is.",
      keywords:["Burden","Overwhelm","Responsibility"]},
    { id:410, name:"Page of Wands", suit:"wands", num:"Page", emoji:"🌟",
      upright:"Creative excitement, bold ideas, and the infectious energy of someone who is not afraid to start before they know how. This page brings news of something new and exciting — or is that new and exciting something you. Channel this fire before it cools.",
      reversed:"Scattered energy, lack of follow-through, or big ideas without any ground to land on. Channel the excitement into one focused direction. Depth, not breadth.",
      keywords:["Enthusiasm","New Ideas","Adventure"]},
    { id:411, name:"Knight of Wands", suit:"wands", num:"Knight", emoji:"🐎",
      upright:"Fearless, passionate, and in full creative motion. This knight does not wait for permission or perfect conditions. He charges. Right now, his energy is yours — use it to pursue what excites you without waiting until the conditions are safer.",
      reversed:"Impulsivity, recklessness, or burning hot and then burning out. The fire is real but without direction, it consumes rather than creates. Find a focal point.",
      keywords:["Passion","Adventure","Impulsiveness"]},
    { id:412, name:"Queen of Wands", suit:"wands", num:"Queen", emoji:"🌻",
      upright:"Magnetic, confident, and fully alive in her own power. This queen knows exactly what she wants and radiates the kind of warmth that draws everything to her. You carry this energy right now. Walk into the room like you own it.",
      reversed:"Jealousy, self-doubt, or a fire that has turned inward and is burning through self-esteem rather than lighting the world. Return to your genuine power. It was never dependent on comparison.",
      keywords:["Confidence","Passion","Charisma"]},
    { id:413, name:"King of Wands", suit:"wands", num:"King", emoji:"🦁",
      upright:"A visionary who makes things happen. This king does not just dream — he builds the dream into reality through force of will, charisma, and inspired leadership. Where is your vision calling you to lead, not just follow?",
      reversed:"Arrogance, impulsivity, or the use of charisma to manipulate rather than inspire. Leadership without integrity eventually empties the room. Return to purpose.",
      keywords:["Visionary","Leadership","Charisma"]},
  ];
}

const FULL_DECK = [
  ...MAJOR_ARCANA,
  ...makeCups(),
  ...makePentacles(),
  ...makeSwords(),
  ...makeWands(),
];

// ── LOVE MESSAGES (30) ────────────────────────────
const LOVE_MESSAGES = [
  { title:"Sacred Recognition", icon:"🌹", keyword:"Soulmate Energy",
    text:"There is a soul in your world right now who sees you — not the version you perform, but the real one. Do not hide from this recognition. It is rare. Allow yourself to be truly seen, even if it frightens you. What is met with genuine presence cannot help but deepen." },
  { title:"The Healing Path", icon:"💫", keyword:"Emotional Renewal",
    text:"A wound you have been carrying — perhaps for years — is finally ready to heal. Love is asking you to stop protecting the tender place and allow it to be touched. The relationship or connection that triggers this healing is not causing the wound; it is revealing it so it can close." },
  { title:"Reciprocal Flow", icon:"🔄", keyword:"Equal Exchange",
    text:"Examine the give-and-take in your closest relationships. Love is not a transaction, but it does require balance. If you are always the one reaching, it may be time to let someone come to you. If you are the one being reached for, consider whether you are truly available." },
  { title:"The Waiting Heart", icon:"🌸", keyword:"Timing",
    text:"What you are hoping for in love is real and possible. But the timing is asking for patience you may not want to give. Trust that genuine connection does not arrive early or late — it arrives when both people are actually ready. Use this time to become more fully yourself." },
  { title:"Honest Ground", icon:"🌱", keyword:"Vulnerability",
    text:"The most intimate thing you can do with another person is tell them your truth — not the palatable version, but the real one. Love built on honesty may feel more exposed, but it is far more durable. What have you been withholding that deserves to be spoken?" },
  { title:"Freedom in Love", icon:"🕊️", keyword:"Independence",
    text:"Love does not require you to disappear into another person. The healthiest connections are those in which both individuals continue to grow, to have their own lives, their own joys, their own silences. Your autonomy is not a threat to love — it is part of what makes you worth loving." },
  { title:"Old Patterns", icon:"🌀", keyword:"Breaking Cycles",
    text:"There is a pattern in your love life that keeps repeating itself under different faces. The names change; the dynamic does not. This cycle is not bad luck — it is a lesson that has not yet been completed. Name the pattern honestly, and the next chapter will be written differently." },
  { title:"Unexpected Arrival", icon:"✨", keyword:"Surprise",
    text:"Love rarely announces itself with fanfare. It often arrives disguised as ordinary conversation, as someone who makes you laugh, as a quiet presence that becomes indispensable. Stay open to what does not look like your plan. The heart's best surprises come from outside the blueprint." },
  { title:"The Inner Beloved", icon:"💕", keyword:"Self-Love",
    text:"Before you can fully love another, you must learn to be a tender presence with yourself. Not the self that performs and achieves — the one underneath, who is uncertain, soft, and real. What would it mean to give that self the same care you freely offer others?" },
  { title:"Deep Waters", icon:"🌊", keyword:"Emotional Depth",
    text:"You are capable of a love that most people only imagine. But depth requires courage — the courage to go where things are messy and real, where nothing is certain, where the heart is genuinely on the line. Do not settle for shallow simply because it feels safer." },
  { title:"The Long View", icon:"🌅", keyword:"Commitment",
    text:"Long-term love is not the excitement of new connection — it is something quieter and far more profound. It is the choice made again and again to stay present, to grow together, to forgive and return. If you have this, honour it. If you want it, build for it." },
  { title:"Gentle Approach", icon:"🌷", keyword:"Tenderness",
    text:"Approach what is tender in your romantic life with more gentleness. Less pressure, less urgency, less analysis. Some things in love grow in silence and patience rather than through effort. What would it feel like to let this particular thing simply unfold?" },
  { title:"After the Storm", icon:"🌈", keyword:"Reconciliation",
    text:"The conflict that has created distance between you and someone important is not the end of the story unless you choose it to be. Reconnection is possible — not through pretending the difficulty did not happen, but through being willing to understand one another across it." },
  { title:"Worthy of Love", icon:"🌟", keyword:"Deservingness",
    text:"There is a quiet voice that sometimes says you are too much, or not enough, for the love you want. It is wrong. The love you long for is not beyond your reach because you are somehow deficient — it has not arrived yet simply because the timing is still aligning. You are worthy, now, exactly as you are." },
  { title:"The Mirror", icon:"🪞", keyword:"Reflection",
    text:"What you most admire in a partner often reflects something you have not fully claimed in yourself. What qualities are you consistently drawn to in others? These are not gifts they have that you lack — they are gifts you are still learning to recognise as your own." },
];

// ── CAREER MESSAGES (30) ─────────────────────────
const CAREER_MESSAGES = [
  { title:"The Rising Tide", icon:"🌅", keyword:"Growth",
    text:"Something that has been quietly building beneath the surface is about to break through. The effort you have made — especially the invisible effort, the work no one sees — is about to become visible. Stay consistent just a little longer. Your breakthrough is not theoretical." },
  { title:"Unconventional Path", icon:"🌿", keyword:"Purpose",
    text:"The path that makes the most sense on paper is not always the one your soul chose to walk. What you have dismissed as impractical may be exactly the direction your deepest capability is pointing. Give the unconventional idea more credit than you have been." },
  { title:"Value Your Work", icon:"⭐", keyword:"Worth",
    text:"You are undervaluing what you bring. Whether it shows up as undercharging, over-delivering, or staying silent in meetings where your contribution would change the outcome — the habit of shrinking your professional value is costing you. Act as though what you do matters. It does." },
  { title:"The Pivot", icon:"🌀", keyword:"Change",
    text:"A change of direction is either underway or necessary. This is not failure — it is the intelligent response to new information about who you are becoming. The career path you are pivoting from taught you exactly what you needed to serve the next chapter. Nothing was wasted." },
  { title:"Collaboration Unlocks", icon:"🤝", keyword:"Teamwork",
    text:"The next significant movement in your career will not come from going it alone. A specific collaboration — a partner, a mentor, a team, a conversation — holds the key to a door you have been trying to force open by yourself. Who are you not asking for help?" },
  { title:"Patience is Power", icon:"🕯️", keyword:"Long Game",
    text:"You are in the season of deep investment, not immediate return. The work you are doing now is more valuable than its current visibility suggests. Mastery is not built in bursts — it is built in the quiet hours when no one is watching and you keep going anyway." },
  { title:"The Abundant Vision", icon:"🌟", keyword:"Abundance",
    text:"Money and meaning are not opposing forces. You are being called toward work that honours your gifts AND your needs simultaneously. Stop settling for one at the expense of the other. The universe supports those who are bold enough to demand both." },
  { title:"Rest as Strategy", icon:"🌙", keyword:"Renewal",
    text:"The most strategic thing you can do right now may be to stop. Not give up — stop. Let the body recover, let the mind wander, let the creative wells refill. The best ideas rarely come from exhausted grinding; they arrive in the margins of restfulness." },
  { title:"Speak Up", icon:"🎺", keyword:"Recognition",
    text:"Your ideas are worth more than the space you allow them. In meetings, in conversations, in applications — there is a version of you that speaks fully, claims the room, and is heard. The gap between that version and your current expression can be narrowed by simply deciding to speak." },
  { title:"The Foundation", icon:"🏛️", keyword:"Stability",
    text:"Before you expand, ensure the foundation can hold what you are building. This is not a caution against dreaming large — it is an invitation to build sustainably. The most impressive structures are the ones still standing a decade later. Build for permanence." },
  { title:"Skills Over Status", icon:"⚙️", keyword:"Mastery",
    text:"The real currency of a long career is not a title — it is skill. What are you genuinely getting better at? Where is the deliberate practice happening? Status can be taken away; deep competence cannot. Invest in the craft beneath the role." },
  { title:"Your Reputation Precedes", icon:"🌺", keyword:"Legacy",
    text:"How do people describe you professionally when you are not in the room? The answer to that question — whether it fills you with pride or discomfort — is useful information about whether your current efforts are building the legacy you actually want." },
  { title:"Trust the Timing", icon:"⏳", keyword:"Divine Timing",
    text:"The opportunity you have been waiting for has not passed — it is being prepared. The universe is not withholding good from you; it is sequencing it. Use the waiting time well. What needs to be ready in you before the right door opens?" },
  { title:"Bold Request", icon:"🔥", keyword:"Negotiation",
    text:"Ask for the raise. Apply for the role. Pitch the idea. Send the proposal. The worst that happens is a 'not yet' — which is infinitely better than the quiet erosion of never knowing. Boldness in professional life is simply the decision to take yourself seriously." },
  { title:"The Calling", icon:"✨", keyword:"Vocation",
    text:"There is something you are here to do that exists at the intersection of your deepest ability and the world's genuine need. If you have found it, protect the time and energy required to pursue it. If you have not, the ache you feel is a compass. Follow it." },
];

// ── YES/NO ANSWERS (30) ───────────────────────────
const YESNO_ANSWERS = [
  { answer:"YES", type:"yes",
    explanation:"The energy surrounding your question is expansive and clear. There are no significant obstacles — only the usual requirement of intention and action. Move toward this with confidence. The universe is not blocking you; it is waiting for you to begin." },
  { answer:"YES", type:"yes",
    explanation:"What you are asking about is aligned with your highest good right now. The conditions are more favourable than they appear. One bold step in this direction will reveal how open the path actually is." },
  { answer:"YES", type:"yes",
    explanation:"The timing is right, the energy is supportive, and the desire behind this question is genuine. Proceed — not recklessly, but with the full belief that this is possible. It is." },
  { answer:"YES", type:"yes",
    explanation:"Something in the universe is actively conspiring to make this happen. You have been more prepared for this than you realise. Lean in." },
  { answer:"YES", type:"yes",
    explanation:"The answer is yes — with the understanding that your continued engagement matters. This is not something that happens to you; it is something you help create. Keep showing up." },
  { answer:"YES", type:"yes",
    explanation:"Not only is this possible — it is more probable than you currently believe. The doubt you feel is old programming, not accurate information. Trust the desire." },
  { answer:"NO", type:"no",
    explanation:"This path carries resistance for a reason. The universe is not punishing you — it is redirecting you. There is something more aligned with who you are becoming just around the corner." },
  { answer:"NO", type:"no",
    explanation:"The energy here does not support this particular outcome right now. This is not a permanent 'no' — it is a timing issue and a direction issue. Ask again after sitting with why you truly want this." },
  { answer:"NO", type:"no",
    explanation:"Something in this request is not aligned with your highest good, even if you cannot see it clearly yet. Trust the resistance. It is protecting you from something you cannot fully see from here." },
  { answer:"NO", type:"no",
    explanation:"The honest answer is no — and the honest follow-up question is: what are you hoping to avoid by getting a yes? That answer holds more insight than this reading." },
  { answer:"NO", type:"no",
    explanation:"This is not your door. Somewhere nearby is one that opens with much less effort — because it was made for you. Do not exhaust yourself forcing this one." },
  { answer:"MAYBE", type:"maybe",
    explanation:"The outcome here is genuinely fluid — it depends on factors that are still in motion, including choices you have not yet made. Your next action carries more weight than you think." },
  { answer:"MAYBE", type:"maybe",
    explanation:"The universe is asking you to refine the question. What you are asking contains a hidden assumption that, if examined, might reveal what you actually want to know. Go deeper." },
  { answer:"MAYBE", type:"maybe",
    explanation:"The conditions are not yet in place for a clear answer. Something is still developing. Wait, watch, and resist the urge to force an outcome before it is ready." },
  { answer:"MAYBE", type:"maybe",
    explanation:"This sits in genuine ambiguity — not because the universe is withholding, but because multiple valid futures are available here. What you choose to believe and do next will determine which one arrives." },
  { answer:"MAYBE", type:"maybe",
    explanation:"This question is asking to be held rather than answered right now. Sit with it for a few more days. The answer will clarify when you are ready to receive it honestly." },
];

// ── GENERAL TAROT MESSAGES (60) ──────────────────
const GENERAL_MESSAGES = [
  "Something within you has been quietly waiting to bloom — not because conditions were not right, but because you were not yet ready to let it. The readiness is arriving now. Trust what is stirring.",
  "The path ahead may feel uncertain, but uncertainty is precisely where transformation lives. You are being asked to release what no longer fits and move forward with open hands. What you let go of will make room for something luminous.",
  "You have been carrying more than most will ever see. The universe sees your quiet strength and is in the process of sending ease your way. You are not behind. You are exactly where your soul arranged to be.",
  "There is an answer forming at the very edge of your awareness. Slow down. Breathe. Let it arrive without chasing it. Some of the most profound truths come like morning light — gently, without announcing themselves.",
  "A cycle is completing, and another is beginning its quiet opening. Do not mourn what is ending; it served its purpose with extraordinary precision. You are at a threshold. What is on the other side is more aligned with who you are now.",
  "Your intuition has been more accurate than you have been willing to admit. The feeling you have been rationalising away? It is correct. The deeper intelligence of your being has been communicating something important, and now is the time to listen fully.",
  "You are more capable of rebuilding than you currently believe. What feels like collapse may simply be the clearing of ground — making space for a foundation that will actually hold. Trust the process even when, especially when, it is uncomfortable.",
  "A door you believed was closed may be quietly reopening. Stay present, stay curious, and do not let old narratives convince you that this is not meant for you. Something is conspiring in your favour in ways you cannot yet fully see.",
  "The energy shifting around you now is not chaos — it is realignment. What once fit no longer does, and this is a sign of your growth, not your inadequacy. Let yourself outgrow what was never truly yours to keep.",
  "You are being called toward a deeper version of yourself. Shallow answers will no longer satisfy. Go inward. Ask the harder questions. The clarity you have been seeking has always been closer than it appeared.",
  "Something you released — a relationship, a belief, a version of yourself — needed to go in order for what is coming to have room. The loss was real. So is what it made possible.",
  "There are people in your life who love you more completely than you currently allow yourself to receive. This is not their limitation. What would it take to let yourself be loved at full capacity?",
  "A creative impulse or project that has been hovering at the edges of your attention deserves to be taken seriously. Not eventually. Now. The world needs what only you can make.",
  "Something small is asking for your attention — a relationship, a habit, a neglected part of yourself. The big changes always begin in the small places. Honour the minor thing today.",
  "You have been waiting for permission that only you can grant. The person whose approval you need is the one who looks back at you from every mirror. Give it.",
  "The anxiety you are carrying about the future is not prophecy — it is a story. The actual future has not been written. And the author of it is you, right now, by how you choose to show up today.",
  "Something is asking to be forgiven — a past version of yourself, someone who hurt you, a decision you made in the dark. Forgiveness is not for them. It is for the part of you that is still held hostage by what happened.",
  "A new collaboration or relationship is forming that will prove to be more significant than it initially appears. Pay attention to who is arriving in your life right now. Some connections are more important than they look at first glance.",
  "The season of effort is shifting into a season of receiving. You have done the work. Now the universe is asking you to stop pushing and allow what you have earned to arrive. Ease is not a sign you are doing something wrong.",
  "What you are most afraid of losing is worth protecting — but not at the cost of your peace. Examine whether what you are guarding is being preserved or whether it is slowly suffocating under too much protection.",
  "Your most honest self — the one beneath the roles and the performances and the careful management of others' perceptions — deserves to be expressed. Not just in private. Out loud, where it might actually change something.",
  "A lesson that has been circling your life, wearing different faces, is asking to be completed. What is the common thread? Name it. Learning it consciously this time will mean you do not have to learn it again.",
  "The part of you that is most uncertain and most tender is also the part that is most real. Do not hide it from the people you are trying to love. Intimacy is only possible where something true is being risked.",
  "You are in the process of becoming someone you cannot quite see yet. This is disorienting — it is also extraordinary. Trust the becoming. The version of you that emerges from this will have earned what they carry.",
  "Something that felt like an ending was actually a beginning wearing the wrong label. Look again at what you decided was a closed door. The light coming through it is from an open window on the other side.",
  "The gifts you most take for granted in yourself are the ones that most move and help the people around you. Stop dismissing what comes naturally to you. Natural is not the same as common.",
  "You are not required to be certain before you begin. Certainty is often the final gift of action, not its prerequisite. Move toward what calls you before you have all the answers. They will arrive in the moving.",
  "Rest is not a luxury right now — it is the most productive thing available to you. The breakthrough you have been working toward requires your nervous system to be in a state of openness, not exhaustion. Sleep. Breathe. Stop.",
  "Someone is thinking of you with more warmth and appreciation than you know. You have impacted a life — perhaps several — in ways that have never been spoken aloud. The love around you is quieter than you realise, and wider.",
  "The universe is asking you to trust one more time — in yourself, in the process, in the worthiness of what you are reaching for. You have been here before and survived. This time, trust that you might also thrive.",
];

// ── DAILY TAROT (12) ─────────────────────────────
const DAILY_CARDS = [
  { icon:"🌙", title:"Trust the Unseen", affirmation:"I trust what I cannot yet see",
    msg:"Today is not a day for forcing answers — it is a day for allowing them to arrive. Something you have been wondering about is resolving itself quietly behind the scenes. Rest in trust, and let the day unfold at its own sacred pace." },
  { icon:"⭐", title:"You Are the Light", affirmation:"I radiate what I seek",
    msg:"The universe placed a specific kind of magic inside you that no one else possesses. Today, you are invited to stop waiting for permission to be exactly who you are. Someone needs the particular light only you can shine." },
  { icon:"🌸", title:"Softness is Strength", affirmation:"My gentleness is my power",
    msg:"The hardest choice is not always the right one. Today, choose the path that honours your nervous system, your heart, and your relationships. Softness is not weakness. It is wisdom wrapped in compassion." },
  { icon:"🌊", title:"Flow, Not Force", affirmation:"I release and I receive",
    msg:"Notice today where you are gripping too tightly. The thing you most want may be waiting for you to relax your hold on how it should arrive. Let the current carry what belongs to you — without swimming upstream to meet it." },
  { icon:"🌿", title:"Rooted and Ready", affirmation:"I am grounded and growing",
    msg:"Before any great expansion, there must be deep roots. Today is a day to ground yourself — in your values, your body, your breath. From this still and steady place, anything you build will last." },
  { icon:"✨", title:"Magic is Ordinary Here", affirmation:"I notice the miraculous",
    msg:"The most profound magic rarely announces itself. It hides in small moments — a perfectly timed message, an unexpected kindness, a pause where something important becomes clear. Stay present today. It is enough." },
  { icon:"☀️", title:"Your Joy is Permission", affirmation:"I allow myself to flourish",
    msg:"You do not need to earn your happiness. Today, do one thing purely because it brings you joy — with no justification, no productivity attached. Your joy is not a distraction from your purpose. It is an expression of it." },
  { icon:"🕯️", title:"The Inner Compass", affirmation:"I trust my own knowing",
    msg:"You already know the answer to the question you keep asking others. Today, sit in the silence long enough to hear your own inner voice. It has been waiting patiently for you to stop and listen." },
  { icon:"🌺", title:"Receiving is Sacred", affirmation:"I am open to receiving",
    msg:"How comfortable are you with receiving — with accepting help, love, compliments, abundance? Today, the universe is asking you to open your hands and your heart. Practice letting good things land without deflecting them." },
  { icon:"🪐", title:"The Bigger Picture", affirmation:"Everything is working for me",
    msg:"Step back from the detail of your day and see the arc of your life. You are not stuck — you are mid-story. What feels like a plateau is often the quiet space before a significant turning point. Keep going." },
  { icon:"🔮", title:"Deep Knowing", affirmation:"My intuition is my greatest gift",
    msg:"There is a wisdom available to you right now that logic cannot fully access. Drop into the body. Notice what it is carrying. The gut feeling, the chest tightness, the unexpected tears — these are data, not disruptions." },
  { icon:"🌒", title:"Sacred Pause", affirmation:"In stillness I find clarity",
    msg:"Not every moment requires action. Today, practice the art of the sacred pause — the breath before the response, the space before the decision, the silence before the choice. What becomes clear when you wait?" },
];

// ── UTILITIES ─────────────────────────────────────
function shuffle(arr) {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

function pick(arr) { return arr[Math.floor(Math.random() * arr.length)]; }
function pickN(arr, n) { return shuffle(arr).slice(0, n); }

function isReversed() { return Math.random() < 0.35; }

function today() {
  return new Date().toLocaleDateString('en-US', {
    weekday: 'long', month: 'long', day: 'numeric', year: 'numeric'
  });
}
